/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsSkillSlugIndexRouteImport } from './routes/skills/$skillSlug/index'
import { Route as SkillsSkillSlugEditeRouteImport } from './routes/skills/$skillSlug/edite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillSlugIndexRoute = SkillsSkillSlugIndexRouteImport.update({
  id: '/skills/$skillSlug/',
  path: '/skills/$skillSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSkillSlugEditeRoute = SkillsSkillSlugEditeRouteImport.update({
  id: '/skills/$skillSlug/edite',
  path: '/skills/$skillSlug/edite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skills/$skillSlug/edite': typeof SkillsSkillSlugEditeRoute
  '/skills/$skillSlug/': typeof SkillsSkillSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skills/$skillSlug/edite': typeof SkillsSkillSlugEditeRoute
  '/skills/$skillSlug': typeof SkillsSkillSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/skills/$skillSlug/edite': typeof SkillsSkillSlugEditeRoute
  '/skills/$skillSlug/': typeof SkillsSkillSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/skills/$skillSlug/edite' | '/skills/$skillSlug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/skills/$skillSlug/edite' | '/skills/$skillSlug'
  id: '__root__' | '/' | '/skills/$skillSlug/edite' | '/skills/$skillSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillsSkillSlugEditeRoute: typeof SkillsSkillSlugEditeRoute
  SkillsSkillSlugIndexRoute: typeof SkillsSkillSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillSlug/': {
      id: '/skills/$skillSlug/'
      path: '/skills/$skillSlug'
      fullPath: '/skills/$skillSlug/'
      preLoaderRoute: typeof SkillsSkillSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$skillSlug/edite': {
      id: '/skills/$skillSlug/edite'
      path: '/skills/$skillSlug/edite'
      fullPath: '/skills/$skillSlug/edite'
      preLoaderRoute: typeof SkillsSkillSlugEditeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillsSkillSlugEditeRoute: SkillsSkillSlugEditeRoute,
  SkillsSkillSlugIndexRoute: SkillsSkillSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
