/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignOutRouteImport } from './routes/(auth)/sign-out'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as dashboardAdminRouteRouteImport } from './routes/(dashboard)/admin/route'
import { Route as dashboardAdminIndexRouteImport } from './routes/(dashboard)/admin/index'
import { Route as ApiCronDiscoveryRouteImport } from './routes/api/cron/discovery'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as dashboardAdminUsersRouteImport } from './routes/(dashboard)/admin/users'
import { Route as dashboardAdminSyncLogsRouteImport } from './routes/(dashboard)/admin/sync-logs'
import { Route as dashboardAdminSubmissionsRouteImport } from './routes/(dashboard)/admin/submissions'
import { Route as dashboardAdminSettingsRouteImport } from './routes/(dashboard)/admin/settings'
import { Route as dashboardAdminReposRouteImport } from './routes/(dashboard)/admin/repos'
import { Route as dashboardAdminDiscoveryRouteImport } from './routes/(dashboard)/admin/discovery'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignOutRoute = authSignOutRouteImport.update({
  id: '/(auth)/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminRouteRoute = dashboardAdminRouteRouteImport.update({
  id: '/(dashboard)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminIndexRoute = dashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardAdminRouteRoute,
} as any)
const ApiCronDiscoveryRoute = ApiCronDiscoveryRouteImport.update({
  id: '/api/cron/discovery',
  path: '/api/cron/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardAdminUsersRoute = dashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => dashboardAdminRouteRoute,
} as any)
const dashboardAdminSyncLogsRoute = dashboardAdminSyncLogsRouteImport.update({
  id: '/sync-logs',
  path: '/sync-logs',
  getParentRoute: () => dashboardAdminRouteRoute,
} as any)
const dashboardAdminSubmissionsRoute =
  dashboardAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => dashboardAdminRouteRoute,
  } as any)
const dashboardAdminSettingsRoute = dashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => dashboardAdminRouteRoute,
} as any)
const dashboardAdminReposRoute = dashboardAdminReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => dashboardAdminRouteRoute,
} as any)
const dashboardAdminDiscoveryRoute = dashboardAdminDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => dashboardAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/skills': typeof SkillsRoute
  '/admin': typeof dashboardAdminRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-out': typeof authSignOutRoute
  '/admin/discovery': typeof dashboardAdminDiscoveryRoute
  '/admin/repos': typeof dashboardAdminReposRoute
  '/admin/settings': typeof dashboardAdminSettingsRoute
  '/admin/submissions': typeof dashboardAdminSubmissionsRoute
  '/admin/sync-logs': typeof dashboardAdminSyncLogsRoute
  '/admin/users': typeof dashboardAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/discovery': typeof ApiCronDiscoveryRoute
  '/admin/': typeof dashboardAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/skills': typeof SkillsRoute
  '/sign-in': typeof authSignInRoute
  '/sign-out': typeof authSignOutRoute
  '/admin/discovery': typeof dashboardAdminDiscoveryRoute
  '/admin/repos': typeof dashboardAdminReposRoute
  '/admin/settings': typeof dashboardAdminSettingsRoute
  '/admin/submissions': typeof dashboardAdminSubmissionsRoute
  '/admin/sync-logs': typeof dashboardAdminSyncLogsRoute
  '/admin/users': typeof dashboardAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/discovery': typeof ApiCronDiscoveryRoute
  '/admin': typeof dashboardAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/skills': typeof SkillsRoute
  '/(dashboard)/admin': typeof dashboardAdminRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-out': typeof authSignOutRoute
  '/(dashboard)/admin/discovery': typeof dashboardAdminDiscoveryRoute
  '/(dashboard)/admin/repos': typeof dashboardAdminReposRoute
  '/(dashboard)/admin/settings': typeof dashboardAdminSettingsRoute
  '/(dashboard)/admin/submissions': typeof dashboardAdminSubmissionsRoute
  '/(dashboard)/admin/sync-logs': typeof dashboardAdminSyncLogsRoute
  '/(dashboard)/admin/users': typeof dashboardAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/discovery': typeof ApiCronDiscoveryRoute
  '/(dashboard)/admin/': typeof dashboardAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/skills'
    | '/admin'
    | '/sign-in'
    | '/sign-out'
    | '/admin/discovery'
    | '/admin/repos'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/sync-logs'
    | '/admin/users'
    | '/api/auth/$'
    | '/api/cron/discovery'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/skills'
    | '/sign-in'
    | '/sign-out'
    | '/admin/discovery'
    | '/admin/repos'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/sync-logs'
    | '/admin/users'
    | '/api/auth/$'
    | '/api/cron/discovery'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/skills'
    | '/(dashboard)/admin'
    | '/(auth)/sign-in'
    | '/(auth)/sign-out'
    | '/(dashboard)/admin/discovery'
    | '/(dashboard)/admin/repos'
    | '/(dashboard)/admin/settings'
    | '/(dashboard)/admin/submissions'
    | '/(dashboard)/admin/sync-logs'
    | '/(dashboard)/admin/users'
    | '/api/auth/$'
    | '/api/cron/discovery'
    | '/(dashboard)/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  SkillsRoute: typeof SkillsRoute
  dashboardAdminRouteRoute: typeof dashboardAdminRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignOutRoute: typeof authSignOutRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronDiscoveryRoute: typeof ApiCronDiscoveryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-out': {
      id: '/(auth)/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof authSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin': {
      id: '/(dashboard)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof dashboardAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/': {
      id: '/(dashboard)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof dashboardAdminIndexRouteImport
      parentRoute: typeof dashboardAdminRouteRoute
    }
    '/api/cron/discovery': {
      id: '/api/cron/discovery'
      path: '/api/cron/discovery'
      fullPath: '/api/cron/discovery'
      preLoaderRoute: typeof ApiCronDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/admin/users': {
      id: '/(dashboard)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof dashboardAdminUsersRouteImport
      parentRoute: typeof dashboardAdminRouteRoute
    }
    '/(dashboard)/admin/sync-logs': {
      id: '/(dashboard)/admin/sync-logs'
      path: '/sync-logs'
      fullPath: '/admin/sync-logs'
      preLoaderRoute: typeof dashboardAdminSyncLogsRouteImport
      parentRoute: typeof dashboardAdminRouteRoute
    }
    '/(dashboard)/admin/submissions': {
      id: '/(dashboard)/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof dashboardAdminSubmissionsRouteImport
      parentRoute: typeof dashboardAdminRouteRoute
    }
    '/(dashboard)/admin/settings': {
      id: '/(dashboard)/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof dashboardAdminSettingsRouteImport
      parentRoute: typeof dashboardAdminRouteRoute
    }
    '/(dashboard)/admin/repos': {
      id: '/(dashboard)/admin/repos'
      path: '/repos'
      fullPath: '/admin/repos'
      preLoaderRoute: typeof dashboardAdminReposRouteImport
      parentRoute: typeof dashboardAdminRouteRoute
    }
    '/(dashboard)/admin/discovery': {
      id: '/(dashboard)/admin/discovery'
      path: '/discovery'
      fullPath: '/admin/discovery'
      preLoaderRoute: typeof dashboardAdminDiscoveryRouteImport
      parentRoute: typeof dashboardAdminRouteRoute
    }
  }
}

interface dashboardAdminRouteRouteChildren {
  dashboardAdminDiscoveryRoute: typeof dashboardAdminDiscoveryRoute
  dashboardAdminReposRoute: typeof dashboardAdminReposRoute
  dashboardAdminSettingsRoute: typeof dashboardAdminSettingsRoute
  dashboardAdminSubmissionsRoute: typeof dashboardAdminSubmissionsRoute
  dashboardAdminSyncLogsRoute: typeof dashboardAdminSyncLogsRoute
  dashboardAdminUsersRoute: typeof dashboardAdminUsersRoute
  dashboardAdminIndexRoute: typeof dashboardAdminIndexRoute
}

const dashboardAdminRouteRouteChildren: dashboardAdminRouteRouteChildren = {
  dashboardAdminDiscoveryRoute: dashboardAdminDiscoveryRoute,
  dashboardAdminReposRoute: dashboardAdminReposRoute,
  dashboardAdminSettingsRoute: dashboardAdminSettingsRoute,
  dashboardAdminSubmissionsRoute: dashboardAdminSubmissionsRoute,
  dashboardAdminSyncLogsRoute: dashboardAdminSyncLogsRoute,
  dashboardAdminUsersRoute: dashboardAdminUsersRoute,
  dashboardAdminIndexRoute: dashboardAdminIndexRoute,
}

const dashboardAdminRouteRouteWithChildren =
  dashboardAdminRouteRoute._addFileChildren(dashboardAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  SkillsRoute: SkillsRoute,
  dashboardAdminRouteRoute: dashboardAdminRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignOutRoute: authSignOutRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronDiscoveryRoute: ApiCronDiscoveryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
